added commit logic in yaml

diff --git a/.github/workflows/qualification.yaml b/.github/workflows/qualification.yaml
--- a/.github/workflows/qualification.yaml
+++ b/.github/workflows/qualification.yaml
@@ -45,15 +45,20 @@ jobs:
           git clone https://github.com/mmumshad/simple-webapp-flask.git my-qual-project
           cp -r my-qual-project my-qual-project-start
           cd my-qual-project-start
-          git config --global  user.name "Github Actions"
-          git config --global user.email "actions@github.com"
-          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf https://github.com/
           cd ..
           tar -cf my-qual-project-start.tar my-qual-project-start
           echo "======================="
           python3 run_gemini.py
           sleep 70
           ls my-qual-project-start
+          git config user.email "actions@github.com"
+          git config user.name "GitHub Actions"
+          cd my-qual-project-start
+          git add GEMINI.md
+          git commit -m "CI: update metadata files [skip ci]" || echo "Nothing to commit"
+          git push || echo "Push failed"
+
+
           echo "==================="
           cat my-qual-project-start-log.log
           echo "==================="
